name: AutoTest Database Setup

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SQL Server
        run: |
          sudo systemctl start mssql-server
          echo "Waiting for SQL Server to start..."
          sleep 10

      - name: Run SQL Scripts
        run: |
          sqlcmd -S localhost -U sa -P 'StrongPassword123!' -i .github/workflows/sql-automation.sql

      - name: Expose SQL Server with LocalTunnel
        run: |
          npm install -g localtunnel
          lt --port 1433 --subdomain myautotestsql &
          sleep 5
          echo "SQL Server exposed at: https://myautotestsql.loca.lt"

      - name: Insert Sample Data
        run: |
          sqlcmd -S localhost -U Auto_user -P 'StrongPassword123!' -d AutoTest -Q "EXEC InsertUserData 'John', 'Doe', 'johndoe@example.com'"

